apiVersion: v1
kind: Secret
metadata:
  name: telegram-chat-secrets
  namespace: telegram-chat
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_USER: cG9zdGdyZXM=  # postgres
  DATABASE_PASSWORD: cG9zdGdyZXM=  # postgres
  
  # JWT secrets (base64 encoded - replace with actual secrets)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl  # your-super-secret-jwt-key-here
  JWT_REFRESH_SECRET: eW91ci1zdXBlci1zZWNyZXQtcmVmcmVzaC1rZXktaGVyZQ==  # your-super-secret-refresh-key-here
  
  # MinIO credentials (base64 encoded)
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==  # minioadmin
  MINIO_SECRET_KEY: bWluaW9hZG1pbjEyMw==  # minioadmin123
  
  # MeiliSearch master key (base64 encoded)
  MEILISEARCH_MASTER_KEY: bWFzdGVyS2V5MTIz  # masterKey123
  
  # Redis password (base64 encoded - optional)
  REDIS_PASSWORD: ""
  
  # Encryption key for data at rest (base64 encoded)
  ENCRYPTION_KEY: eW91ci0zMi1ieXRlLWVuY3J5cHRpb24ta2V5LWhlcmU=  # your-32-byte-encryption-key-here