global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Chat API metrics
  - job_name: 'chat-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # Node.js application metrics
  - job_name: 'chat-api-nodejs'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # k6 load test metrics
  - job_name: 'k6-tests'
    static_configs:
      - targets: ['k6-prometheus-adapter:9090']
    scrape_interval: 5s
    honor_labels: true